### ISSUE TITLE
AuditApi does not work with integration tests using TestServer

### ISSUE THREAD

**Issue by fernandovictorTI** [thepirat000/Audit.NET#102]
Hi,
I created a base controler with the [AuditApi] tag, for all my requests to be written to the database.
```
[AuditApi]
public class BaseAuroraController : ControllerBase
```
It's all working, I'm doing the integration tests and it's giving 'Object reference not set to an instance of an object.', when comment [AuditApi] tests normally work.

I'm using Dotnetcore 2.0 with the audit versions
```
<PackageReference Include = "Audit.Mvc.Core" Version = "11.0.5" />
<PackageReference Include = "Audit.WebApi.Core" Version = "11.0.5" />
```
Can you help me?

**Comment by thepirat000** [comment]
Did you setup the data provider or any configuration on your statrup code?

Please check the [configuration section](https://github.com/thepirat000/Audit.NET#configuration) on the readme file.

By default, it will try to log to files, by creating files on the running directory.

Can you please share the stacktrace on the exception?

**Comment by fernandovictorTI** [comment]
I'm setting up on my Startup

```
Audit.Core.Configuration.Setup().UseCustomProvider(new AuroraMongoDataProvider(connectionStringMongo, databaseMongo));
```

```
public class AuroraMongoDataProvider : MongoDataProvider
    {
        public AuroraMongoDataProvider(string connectionString, string database, string tabela = "Auditoria")
        {
            ConnectionString = connectionString;
            Database = database;
            Collection = tabela;
        }
    }
```

My stacktrace on the exception

```
   at Audit.WebApi.AuditApiAttribute.<BeforeExecutingAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Audit.WebApi.AuditApiAttribute.<OnActionExecutionAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PJMT.Aurora.API.Middlewares.ErrorHandlingMiddleware.<Invoke>d__4.MoveNext() in D:\GIT\Aurora-Backend-DotNet-Seed\src\PJMT.Aurora.API\Middlewares\ErrorHandlingMiddleware.cs:line 48
```

**Comment by fernandovictorTI** [comment]
Same stacktrace using 

```
Audit.Core.Configuration.Setup()
    .UseDynamicProvider(_=> _
        .OnInsert(ev => Console.WriteLine($"{ev.Environment.UserName}")));
```

```
   at Audit.WebApi.AuditApiAttribute.<BeforeExecutingAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Audit.WebApi.AuditApiAttribute.<OnActionExecutionAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PJMT.Aurora.API.Middlewares.ErrorHandlingMiddleware.<Invoke>d__4.MoveNext() in D:\GIT\Aurora-Backend-DotNet-Seed\src\PJMT.Aurora.API\Middlewares\ErrorHandlingMiddleware.cs:line 48
```

**Comment by thepirat000** [comment]
Can you share a test code that fails? I was unable to reproduce this yet

**Comment by thepirat000** [comment]
I've created a WebAPI project with your configuration and have had no problems. Could you please test is this sample project gives you the exception?

[WebApplication1.zip](https://github.com/thepirat000/Audit.NET/files/1791109/WebApplication1.zip)

**Comment by fernandovictorTI** [comment]
The error is exactly in this line, I downloaded the project and added it in mine to debug.
```
IpAddress = httpContext.Connection? .RemoteIpAddress.ToString (),
```

RemoteIpAddress is coming null

**Comment by thepirat000** [comment]
ok, I will provide a fix for that

**Comment by fernandovictorTI** [comment]
Example


[DotNetCoreAuditApiWithMongoIntegrationTests.zip](https://github.com/thepirat000/Audit.NET/files/1791206/DotNetCoreAuditApiWithMongoIntegrationTests.zip)

**Comment by fernandovictorTI** [comment]
Working perfectly, Thanks.
