### ISSUE TITLE
EntityKeyHelper NullReferenceExceptions

### ISSUE THREAD

**Issue by afark** [thepirat000/Audit.NET#150]
**Describe the bug**
We are using EF auditing in an API application and gets  NullReferenceExceptions in different methods of EntityKeyHelper. See stack traces below. 

The exceptions could possible be caused by multiple threads trying to modify the  cache dictionaries in EntityKeyHelper. See this stackoverflow question's accepted answer as reference: https://stackoverflow.com/questions/1320264/how-did-i-get-this-nullreferenceexception-error-here-right-after-the-constructor

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EntityKeyHelper.GetKeyNames(DbContext context, Type entityType)
   at EntityKeyHelper.GetPrimaryKeyValues(Object entity, DbContext context)
   at Audit.EntityFramework.DbContextHelper.GetPrimaryKey(DbContext dbContext, DbEntityEntry entry)
   at Audit.EntityFramework.DbContextHelper.UpdateAuditEvent(EntityFrameworkEvent efEvent, IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.SaveScope(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChanges()

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EntityKeyHelper.GetColumnName(Type type, String propertyName, DbContext context)
   at Audit.EntityFramework.DbContextHelper.GetChanges(IAuditDbContext context, DbEntityEntry entry)
   at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChanges()

**To Reproduce**
Setting up a test project causing multiple SaveChanges calls from different threads simultaneously.

**Expected behavior**
No exceptions should be thrown.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET: 12.1.7
 - Audit.EntityFramework: 12.1.7

**Comment by thepirat000** [comment]
You are right, I've added a stress test with multiple threads modifying an audited dbcontext and got the exception. 

This is fixed in the new version (12.3.5). I've changed Dictionaries to Concurrent Dictionaries.

Please upgrade your references and reply to this if you're still having problems.
