### ISSUE TITLE
When I enable IncludeEntityObjects my seed data crashes

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#199]
This is from my unit tests after I place a `[AuditDbContext(IncludeEntityObjects = true)]` on top of my context. I will also say fluent `.IncludeEntityObjects()` does not seem to work. My Entity is still null. Only the context `AuditDbContext` attribute seems to work. Is this a bug?

I even tried `Audit.Core.Configuration.DataProvider = new NullDataProvider();` with no success. I even still get audit events in .json format in my test directory.

```
at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at System.IO.StringWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextWriter.WriteIndent() in /_/Src/Newtonsoft.Json/JsonTextWriter.cs:line 333
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type) in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 773
   at Newtonsoft.Json.JsonWriter.WriteEnd(JsonContainerType type) in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 715
   at Newtonsoft.Json.JsonWriter.WriteEnd() in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 492
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll() in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 729
   at Newtonsoft.Json.JsonWriter.Close() in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 415
   at Newtonsoft.Json.JsonTextWriter.Close() in /_/Src/Newtonsoft.Json/JsonTextWriter.cs:line 185
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing) in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 1466
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose() in /_/Src/Newtonsoft.Json/JsonWriter.cs:line 1454
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 665
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 613
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 591
   at Audit.Core.Providers.FileDataProvider.InsertEvent(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEvent(Boolean forceInsert)
   at Audit.Core.AuditScope.Save()
   at Audit.EntityFramework.DbContextHelper.SaveScope(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChanges()
   at MyApp.Infrastructure.Data.FakeData.IdentityInsertSave(MyAppDbContext context, String table) in C:\Source\BBEEWT\iamm.web.service.MyApp\src\MyApp.Infrastructure\FakeData.cs:line 734
   at MyApp.Infrastructure.Data.FakeData.Seed(IServiceProvider serviceProvider) in C:\Source\BBEEWT\iamm.web.service.MyApp\src\MyApp.Infrastructure\FakeData.cs:line 562
   at MyApp.API.IntegrationTests.Configuration.CustomConfigurationWebApplicationFactoryFixture`1.<>c.<ConfigureWebHost>b__2_0(IServiceCollection services) in C:\Source\BBEEWT\iamm.web.service.MyApp\tests\MyApp.API.IntegrationTests\Configuration\CustomConfigurationWebApplicationFactory.cs:line 85
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateServer(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at MyApp.API.IntegrationTests.InventoryServerTests.Update_Success() in C:\Source\BBEEWT\iamm.web.service.MyApp\tests\MyApp.API.IntegrationTests\InventoryServerTests.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.


```

**Comment by thepirat000** [comment]
You should provide a complete sample code that reproduces the error. I guess you have some custom action or any other configuration that is messing up.

**Comment by VictorioBerra** [comment]
Yeah something is odd with my WebApplicationFactory. If I put the NullDataProvider in the WebApplicationFactory I do not get the error.
