### ISSUE TITLE
Audit.net caused 2 issues for OData web api calls.

### ISSUE THREAD

**Issue by fzhangddt** [thepirat000/Audit.NET#233]
**Describe the bug**
Audit.net caused 2 issues for OData web api calls.

Set Up:
we use AuditApiGlobalFilter. We mark Odata related controllers as [AuditIgnore], which are derived from ODataBaseController. Out intent is to Audit all controllers except the ones marked with [AuditIgnore].

When making OData calls, we see 2 issues from Audit.WebApi:

### 1) Looks like Audit.WebAPI doesn't ignore those controllers. Audit throws NullReferenceException when it tries to save AuditEvent to sql server. Here is the stack trace. Since the controller is marked [AuditIgnore], i don't expect Audit.Core.AuditScope call SaveSync().

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at Newtonsoft.Json.JsonTextWriter.WriteIndent()
   at Newtonsoft.Json.JsonWriter.AutoCompleteClose(JsonContainerType type)
   at Newtonsoft.Json.JsonWriter.WriteEndObject()
   at Newtonsoft.Json.JsonWriter.AutoCompleteAll()
   at Newtonsoft.Json.JsonTextWriter.Close()
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing)
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Audit.Core.AuditEvent.ToJson()
   at Audit.SqlServer.Providers.SqlDataProvider.GetParametersForInsert(AuditEvent auditEvent)
   at Audit.SqlServer.Providers.SqlDataProvider.<InsertEventAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Audit.Core.AuditScope.<SaveEventAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Audit.Core.AuditScope.<SaveAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Audit.WebApi.AuditApiAdapter.<AfterExecutedAsync>d__2.MoveNext()
```

### 2) Audit creates tons of char[]. In my case, Odata api call retrieves 1248 items. Audit creates over 500,000 of char[]. Each char[] has the same length, 16024. The content is unicode json string. The json contains a lot of space. 500,000 *16,024 = 8G. This cased the memory of w3wp.exe jumped very high (9G bytes) and very fast (within 1 minute).

Since the controller is marked as [AuditIgnore], I would expect Audit doesn't do processing about the api call.

After I turn off Audit, the same OData api call finishes within 1 second and the memory of w3wp.exe didn't jump.

I attached a char[].
[1CharArray.txt](https://github.com/thepirat000/Audit.NET/files/3427933/1CharArray.txt)

**To Reproduce**
Please see above description.

**Expected behavior**
When the controller is marked with [AuditIgnore], Audit should check the flag at the beginning and return immediately.

**Libraries (specify the Audit.NET extensions being used including version):**
We use 3:
 - Audit.WebApi: 14.5.3
 - Audit.Net.SqlServer: 14.5.3
- Audit.Net: 14.5.3

**Additional context**
We are using Asp.net MVC 4.6 and EF 6.2.

**Comment by thepirat000** [comment]
I'm not very familiar with OData. Could you share samples of your controller code so I can reproduce the issue

**Comment by fzhangddt** [comment]
Here is a sample code. The key of Get() method is to return IQueryable<>, It retrieves data from sql server table.
CreateQuery() calls SharpRepository.CreateQuery().

In order for you to reproduce, you don't need to use SharpRepository. You can use EF to get IQueryable.

ODataBaseController eventually inherits from ApiController.

```
[ODataRoutePrefix(ENDPOINT)]
[AuditIgnore]
public class ODataPartController : ODataBaseController
{
    public const string ENDPOINT = "part";

    [ODataRoute]
    public IQueryable<Part> Get(ODataQueryOptions options)
    {
        using (var manager = new PartDetailManager(this._engine.Context))
        {
            var query = manager.CreateQuery();

            return options.ApplyTo(query.OrderBy(obj => obj.Id), this._oDataQuerySettings) as IQueryable<Part>;
        }
    }
}

```

**Comment by thepirat000** [comment]
One more please, can you show how do you attach and configure the `AuditApiGlobalFilter` ?

**Comment by fzhangddt** [comment]
Inside Application_Start, we call GlobalConfiguration.Configure(WebApiConfig.Register), Inside Register method:
public static void Register(HttpConfiguration config), we added AuditGlobalFilter

```
            config.Filters.Add(new AuditApiGlobalFilter(_ => _
                .LogAllActions()
                .WithEventType(Services.Constants.AuditEventNames.API_DIAGNOSTICS)
                .IncludeHeaders()
                .IncludeRequestBody()
                .IncludeResponseHeaders()
                .IncludeResponseBody()));
```

Inside OwinStartup, we have this:

```
private void ConfigureAuditLogging()
        {
            // Configre Audit.NET DataSource
            Audit.Core.Configuration.Setup()
                .UseSqlServer(config => config
                    .ConnectionString(ConfigurationManager.ConnectionStrings[Storage.Constants.Database.DEFAULT_CONNECTION_STRING_NAME].ConnectionString)
                    .Schema("dbo")
                    .TableName("AuditEvents")
                    .IdColumnName("Id")
                    .JsonColumnName("JsonData")
                    .LastUpdatedColumnName("DateUpdated")
                    .CustomColumn("EventType", ev => ev.EventType));

            Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
            {
                var settings = DependencyResolver.Current.GetService<DTO.Settings.EngineSettings>();

                // Disable WebAPI audit logging if `Context.Settings.EnableWebApiAuditLogging`=false
                if (scope.EventType == Services.Constants.AuditEventNames.API_DIAGNOSTICS && !(settings?.EnableWebApiAuditLogging ?? false))
                {
                    scope.Discard();
                }
            });
        }

```

**Comment by thepirat000** [comment]
Still unable to reproduce. 

I've tried with an OData v3 controller on a new webapi project targeting .net framework 4.6.1, with the global filter configured as you, and the `[AuditIgnore]` on the controller is behaving as expected, ignoring the odata calls.

I'm attaching the sample project (Start the app and navigate to "odata/ODataModels")

[Issue233.zip](https://github.com/thepirat000/Audit.NET/files/3428699/Issue233.zip)

**Comment by thepirat000** [comment]
Any update on this?

**Comment by fzhangddt** [comment]
Sorry for the late. I got build error for Issue233 because it references a local project below which I don't have. I am going to write a sample project which can reproduce.

`Import Project="..\..\MIOS\Proyectos .NET\Audit.NET\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props
`

**Comment by thepirat000** [comment]
oh, dumb Visual Studio....  

Please try removing the `..\..\MIOS\Proyectos .NET\Audit.NET\` portion on the hint paths, leaving them as `packages\...`

**Comment by thepirat000** [comment]
I'm closing this for inactivity and unable to reproduce. If you are still having problems, please try to generate a complete sample that is failing to re-open this issue
