### ISSUE TITLE
Audit.net.webapi issue on aspnetcore3

### ISSUE THREAD

**Issue by superkat1111** [thepirat000/Audit.NET#259]
Getting the following error when trying to implement as middleware (sample from template).

Updated to latest version and issue remains.

Any ideas?

System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Audit.WebApi.AuditApiHelper.GetRequestBody(HttpContext httpContext)
   at Audit.WebApi.AuditMiddleware.BeforeInvoke(HttpContext context, Boolean includeHeaders, Boolean includeRequestBody, String eventTypeName)
   at Audit.WebApi.AuditMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by thepirat000** [comment]
This is because of this [[Announcement] AllowSynchronousIO disabled in all servers](https://github.com/aspnet/AspNetCore/issues/7644)
And the library trying to get the request/response body stream copied i.e.: https://github.com/thepirat000/Audit.NET/blob/3469dcb0fbd213f9a0335f33deaf34ff8c2e98ea/src/Audit.WebApi/AuditApiHelper.cs#L100

A workaround is to allow sync IO operations [as shown here](https://stackoverflow.com/a/55196057/122195)

Anyway I'll work on making that call asynchronous on the next version of Audit.WebApi so no workaround would be needed.

**Comment by thepirat000** [comment]
This is fixed on version 14.9.1, please upgrade and re-test

**Comment by thepirat000** [comment]
Closing this for inactivity. If you are still having this issue please comment here

**Comment by salarzobir** [comment]
Same issue in Audit.Mvc

**Comment by thepirat000** [comment]
This was fixed on Audit.Mvc and Audit.Mvc.Core version 16.3.3

Please upgrade your references and re-test

**Comment by salarzobir** [comment]
> This was fixed on Audit.Mvc and Audit.Mvc.Core version 16.3.3
> 
> Please upgrade your references and re-test

Thank you, it is working now
