### ISSUE TITLE
AzureTableDataProvider Concurrency Issues

### ISSUE THREAD

**Issue by MarioPrabowo** [thepirat000/Audit.NET#268]
**Describe the bug**
I got this error randomly thrown:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Audit.AzureTableStorage.Providers.AzureTableDataProvider.EnsureTable(String cnnString, String tableName)
   at Audit.AzureTableStorage.Providers.AzureTableDataProvider.EnsureTable(AuditEvent auditEvent)
   at Audit.AzureTableStorage.Providers.AzureTableDataProvider.InsertEventAsync(AuditEvent auditEvent)`

Upon investigation, I noticed that https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.AzureStorage/Providers/AzureTableDataProvider.cs is using static dictionary internally which is not thread-safe.

**To Reproduce**
Call InsertEventAsync from multiple threads simultaneously.

**Expected behavior**
No errors thrown.

**Libraries (specify the Audit.NET extensions being used including version):**
- Audit.NET.AzureStorage: 14.0.3
 - Audit.EntityFramework: 14.0.3

**Additional context**
This seems similar to https://github.com/thepirat000/Audit.NET/issues/150. Changing it to ConcurrentDictionary should fix it, although I'm not sure how to write tests for it.

**Comment by thepirat000** [comment]
Fixed on 15.0.1, please update your references
