### ISSUE TITLE
Audit.EntityFramework.Identity.Core error with custom entitites

### ISSUE THREAD

**Issue by phobos04** [thepirat000/Audit.NET#293]
**Describe the bug**
I'm using the Audit.EntityFramework.Identity.Core extension for Identity DB Context auditing.
I've got custom types for all the Identity entities, and I cannot correctly audit entities derived from IdentityUserClaim<TKey>, IdentityUserLogin<TKey>, IdentityUserToken<TKey>, IdentityRoleClaim<TKey>, as they're not recognized by the audit DB context.
This is the exception message I get while trying to edit my Role Claims:
```
The entity type 'ApplicationRoleClaim' was not found. Ensure that the entity type has been added to the model.
in    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges(Object entity)
   at Microsoft.EntityFrameworkCore.DbContext.AddAsync(Object entity, CancellationToken cancellationToken)
   at Audit.EntityFramework.Providers.EntityFrameworkDataProvider.InsertEventAsync(AuditEvent auditEvent)
   at DC.Web.Services.AuditNet.EfCustomProvider.InsertEventAsync(AuditEvent auditEvent) in \Services\AuditNet\EFCustomProvider.cs:line 41
   at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
   at Audit.Core.AuditScope.SaveAsync()
   at Audit.EntityFramework.DbContextHelper.SaveScopeAsync(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func`1 baseSaveChanges)
   at DC.Web.Data.IdentityDbContext.SaveChangesAsync(CancellationToken cancellationToken) in \Data\Identity\IdentityDbContext.cs:line 101
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.SaveChanges(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.UpdateAsync(TRole role, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.RoleManager`1.UpdateRoleAsync(TRole role)
   at Microsoft.AspNetCore.Identity.RoleManager`1.RemoveClaimAsync(TRole role, Claim claim)
   at DC.Web.Controllers.RoleController.Edit(String id, Role model) in \Controllers\RoleController.cs:line 294
```

**To Reproduce**
Inherit the IdentityDbContext with full custom types from AuditIdentityDbContext, and then try to edit Identity-related data (e.g. role claims).

**Expected behavior**
Audit of all Identity related custom entities as per Audit.NET configuration using DbContext inheritance.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework.Core: 15.1.0
 - Audit.EntityFramework.Identity.Core: 15.1.0

**Additional context**
All my Identity entities inherit from both Microsoft.AspNetCore.Identity.Identity<EntityNameHere>, and from an interface IAuditableEntity I've created with auditing data:
```
public class ApplicationUser : IdentityUser, IEntityWithFirstNameLastName, IAuditableEntity
public class ApplicationUserClaim : IdentityUserClaim<string>
public class ApplicationUserLogin : IdentityUserLogin<string>
public class ApplicationUserToken : IdentityUserToken<string>
public class ApplicationRole : IdentityRole, IAuditableEntity
public class ApplicationRoleClaim : IdentityRoleClaim<string>
public class ApplicationUserRole: IdentityUserRole<string>, IAuditableEntity
```
This is my IdentityDbContext. I've got the same strange behaviour without inheriting from `AuditIdentityDbContext`, as per [this guideline](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#without-inheritance).
```
public class IdentityDbContext : AuditIdentityDbContext<ApplicationUser, ApplicationRole, string, ApplicationUserClaim, ApplicationUserRole, ApplicationUserLogin, ApplicationRoleClaim, ApplicationUserToken>
{
	public IdentityDbContext(DbContextOptions<IdentityDbContext> options): base(options)
	{
	}

	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);

		builder.HasDefaultSchema("Identity");

		builder.Entity<ApplicationUser>(entity =>
		{
			entity.HasMany(e => e.UserRoles)
			.WithOne(r => r.User)
			.HasForeignKey(e => e.UserId)
			.IsRequired();

			entity.HasMany(e => e.Claims)
			.WithOne(c => c.User)
			.HasForeignKey(e => e.UserId)
			.IsRequired();

			entity.HasMany(e => e.Logins)
			.WithOne(l => l.User)
			.HasForeignKey(e => e.UserId)
			.IsRequired();

			entity.HasMany(e => e.Tokens)
			.WithOne(l => l.User)
			.HasForeignKey(e => e.UserId)
			.IsRequired();

			entity.ToTable(nameof(ApplicationUser));
		});

		builder.Entity<ApplicationRole>(entity =>
		{
			entity
			.HasMany(e => e.UserRoles)
			.WithOne(r => r.Role)
			.HasForeignKey(e => e.RoleId)
			.IsRequired()
			.OnDelete(DeleteBehavior.Restrict);

			entity.HasMany(e => e.Claims)
			.WithOne(c => c.Role)
			.HasForeignKey(e => e.RoleId)
			.IsRequired();

			entity.ToTable(nameof(ApplicationRole));
		});

		builder.Entity<ApplicationUserRole>().ToTable(nameof(ApplicationUserRole));
		builder.Entity<ApplicationUserClaim>().ToTable(nameof(ApplicationUserClaim));
		builder.Entity<ApplicationUserLogin>().ToTable(nameof(ApplicationUserLogin));
		builder.Entity<ApplicationUserToken>().ToTable(nameof(ApplicationUserToken));
		builder.Entity<ApplicationRoleClaim>().ToTable(nameof(ApplicationRoleClaim));
	}

	public override int SaveChanges()
	{
		return base.SaveChanges();
	}

	public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
	{
		return await base.SaveChangesAsync(cancellationToken);
	}
}
```
This is the relevant part of my Audit.NET configuration in my Startup.cs file
```
var auditDbContextOptions = new DbContextOptionsBuilder<AppAuditDbContext>()
	.UseSqlServer(connectionString)
	.Options;

var svcProvider = services.BuildServiceProvider();

/*
 * Include related entitites
 * https://stackoverflow.com/a/54730255/6011874
 */
Audit.EntityFramework.Configuration.Setup()
	.ForAnyContext(_ => _
	.IncludeEntityObjects()
	);

Audit.Core.Configuration.Setup()
	.UseCustomProvider(new EfCustomProvider(config => config
		.UseDbContext<AppAuditDbContext>(auditDbContextOptions)
		.AuditTypeNameMapper(typeName =>
		{
			return typeName;
		}).AuditEntityAction<IAuditableEntity>((ev, ent, auditEntity) =>
		{
			if (!(ev is AuditEventEntityFramework efEvent)) return;

			var entityFrameworkEvent = efEvent.GetEntityFrameworkEvent();
			if (entityFrameworkEvent == null) return;

			auditEntity.AuditUser = svcProvider.GetService<IHttpContextAccessor>().HttpContext?.User?.Identity?.Name ?? $"[{efEvent.Environment.UserName}]";
			auditEntity.AuditAction = ent.Action;

			// Scope ID
			if (ev.CustomFields.TryGetValue("AuditScopeId", out object scopeId))
				auditEntity.AuditScopeId = Guid.Parse(scopeId.ToString());
		})));

// EF AuditScopeId per scope
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	var efAction = scope.Event.GetEntityFrameworkEvent();
	if (efAction == null) return;

	var id = Guid.NewGuid();
	scope.SetCustomField("AuditScopeId", id);
});
```
The `CustomEFProvider` I use is there because I need to audit both EntityFramework and WebApi events. For this context it simply behaves like wrapper arond an `EntityFrameworkDataProvider`.

**Comment by thepirat000** [comment]
Do you have a `ApplicationRoleClaim` table on the audit database?

**Comment by phobos04** [comment]
Yes, I do, but I had to manually create tables for
```
Identity.ApplicationRoleClaim
Identity.ApplicationUserClaim
Identity.ApplicationUserToken
Identity.ApplicationUserLogin
```
These tables mimic my entities, with some added audit related data.

I'm using a separated `AuditDbContext` for my auditing needs. I took inspiration from [this SO thread](https://stackoverflow.com/questions/57780463/how-do-i-target-another-database-with-audit-net-audit-entityframework-core/57829615#57829615) to manage the separated `AuditDbContext`. 

Using this tecnique, the "automatic" entity duplication from my identity context via migrations succeeded for `ApplicationUser`, `ApplicationRole` and `ApplicationUserRole`, but I could not manage to automatically get it for `ApplicationRoleClaim`, `ApplicationUserClaim`, `ApplicationUserToken` and `ApplicationUserLogin`. That's why I wrote that I had to manually create tables for those entities.

I also tried to both inherit from `AuditIdentityDbContext`, as well as using my `IdentityDbcontext` without inheritance, as per [your guidelines](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#without-inheritance), but the result I had were the same.

What could I do to solve this issue?
Thanks!

**Comment by phobos04** [comment]
After further analysis I've spotted the problem. 
It was my fault with the configuration of the `Identity.ApplicationRoleClaim`, `Identity.ApplicationUserClaim`, `Identity.ApplicationUserToken`, `Identity.ApplicationUserLogin` entities.
Now the audit on the `IdentityDbContext` is working properly.
Thank you for your cooperation.
