### ISSUE TITLE
System.InvalidOperationException: Parameter 'c1' must have its value set

### ISSUE THREAD

**Issue by jarmolukd** [thepirat000/Audit.NET#303]
**Describe the bug**
After creating `event` table and setting up auditing in `startup.cs` as outlined in README, the following error is occurring: 

```
2020-06-29T13:18:09.858-05:00 | [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
  | 2020-06-29T13:18:09.858-05:00 | Connection id "0HM0SATF3LV97", Request id "0HM0SATF3LV97:00000001": An unhandled exception was thrown by the application.
  | 2020-06-29T13:18:09.858-05:00 | System.InvalidOperationException: Parameter 'c1' must have its value set
  | 2020-06-29T13:18:09.858-05:00 | at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
  | 2020-06-29T13:18:09.858-05:00 | at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
  | 2020-06-29T13:18:09.858-05:00 | at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
  | 2020-06-29T13:18:09.858-05:00 | at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
  | 2020-06-29T13:18:09.858-05:00 | at Audit.PostgreSql.Providers.PostgreSqlDataProvider.InsertEventAsync(AuditEvent auditEvent)
  | 2020-06-29T13:18:09.858-05:00 | at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
  | 2020-06-29T13:18:09.858-05:00 | at Audit.Core.AuditScope.SaveAsync()
  | 2020-06-29T13:18:09.858-05:00 | at Audit.WebApi.AuditApiAdapter.AfterExecutedAsync(ActionExecutedContext context, Boolean includeModelState, Boolean includeResponseBody, Boolean includeResponseHeaders)
  | 2020-06-29T13:18:09.858-05:00 | at Audit.WebApi.AuditApiAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
  | 2020-06-29T13:18:09.858-05:00 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Prior to making changes to `startup.cs` for configuration of `PostgreSqlDataProvider`, all API endpoints worked as expected.

**To Reproduce**
- Create `event` table using this SQL script: https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/SqlScript.sql
- Setup `PostgreSqlDataProvider` in Startup.cs as outlined here: https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.PostgreSql The `event` table was created in a different schema, so I also set the `Schema` setting here as well. Here is my setup: 
```
Audit.Core.Configuration.DataProvider = new PostgreSqlDataProvider()
            {
                ConnectionString = ConnectionString,
                Schema = "my_schema_name",
                TableName = "event",
                IdColumnName = "id",
                DataColumnName = "data",
                DataType = "JSONB",
                LastUpdatedDateColumnName = "updated_date",
                CustomColumns = new List<CustomColumn>()
                {
                    new CustomColumn("event_type", ev => ev.EventType),
                    new CustomColumn("user", ev => ev.Environment.UserName)
                }
            };
```
- Hit any web API end point in project.

**Expected behavior**
No error. Event to be logged for API end point that was accessed. 

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET.Postgresql 15.2.2

**Comment by thepirat000** [comment]
I was not able to reproduce this issue. My Web API actions was logged correctly.

 Could you share a ready to run project that exposes the issue?

I've tried with the following SQL code to create the table (note this is not the same as in https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/SqlScript.sql):

```SQL
CREATE TABLE public.event
(
    id SERIAL NOT NULL,
    inserted_date timestamp without time zone NOT NULL DEFAULT now(),
    updated_date timestamp without time zone NOT NULL DEFAULT now(),
    data jsonb NOT NULL,
    event_type varchar(50) NULL,
    "user" varchar(50) NULL,
    CONSTRAINT event_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

```

**Comment by jarmolukd** [comment]
Thank you! I believe the issue had to do with the `user` column. I removed the `user` custom column and I'm no longer getting the error, and I'm getting successful audit records. I'll try to add the `user` column back in using the revised create table you've provided.

**Comment by thepirat000** [comment]
oh I see. I've also changed the script on https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/SqlScript.sql
