### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by bottlezz** [thepirat000/Audit.NET#32]
Hi,
I encountered a issue when using AuditScope in my MVC application like below.

`AuditScope.CreateAndSave("LoginSuccess", new { username = user.username });`

`AuditScope.CreateAndSave("LoginFailed", new { username = user.username });`

I have several controller action calls the log , however it doesn't always error out. Sometime it throws exception, and some time it works well.
the exception message is as the title:

> Collection was modified; enumeration operation may not execute.

the stack trace logged as follows:

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at Audit.Core.Configuration.InvokeScopeCustomActions(ActionType type, AuditScope auditScope)
>    at Audit.Core.AuditScope.SaveEvent(Boolean forceInsert)
>    at Audit.Core.AuditScope..ctor(String eventType, Func`1 target, Object extraFields, AuditDataProvider dataProvider, Nullable`1 creationPolicy, Boolean isCreateAndSave)
>    at Audit.Core.AuditScope.CreateAndSave(String eventType, Object extraFields, AuditDataProvider dataProvider)

So my when i looked up the source code, in the class **Audit.Core.Configuration** , you have
```
internal static void InvokeScopeCustomActions(ActionType type, AuditScope auditScope)
{
            foreach (var action in AuditScopeActions[type])
            {
                action.Invoke(auditScope);
            }
}
```

the above function loop through the **AuditScopeActions** Dictionary defined as 

` internal static Dictionary<ActionType, List<Action<AuditScope>>> AuditScopeActions { get; private set; }`

Could that be because the Dictionary isn't thread safe, so when multiple thread from my MVC web application reads and writes it concurrently, it throws the error?

let me know if i am mistaken. thank you.

**Comment by thepirat000** [comment]
Yes, you are right! but the problem is with the List<Action<AuditScope>> and not with the dictionary itself.

It seems you're adding custom actions at the same time some audit events are being saved. That provokes the exception.

I just made a change to make the collection thread safe, so now you can add custom actions and create events at the same time, although this is not recommended (you should define your custom actions before starting to audit).

Please download and use the latest version of the library (>= 6.2.0) and feel free to reopen this issue is you're still having problems.

Thanks!

**Comment by bottlezz** [comment]
Thank you very much for the quick response and update. We have tested in our environment, it fixed the issue and working well.
However, to my personal interests, I have a  question: I have seen in many other ASP.NET sample projects   people use ConcurrentDictionary quite often. My coworker did a small performance test, it does seem  concurrentQueue runs slightly faster than Locking List. I did some fast research, but couldn't find a good answer on how concurrent collections works different than locks.  So I wonder if you may have better idea?
thanks again for you time and effort.

**Comment by thepirat000** [comment]
I think performance is not a concern here, since adding custom actions ideally should not be executed multiple times, just once at the start-up, also the locking that happens when **executing actions** should be fast enough since it just locks the list to get a copy of the delegates, and releases the lock before calling the actions.

Do you have a use case in which you need to keep adding/removing custom actions while your application is running?

Anyway, I'll keep this open to analyze if it should be better to use events for this _observer pattern_

**Comment by bottlezz** [comment]
Thanks for your explain. And yes, lock doesn't make any noticeable performance difference after i updated the Nuget package.
Right now, our current code seems using custom actions for all auditing. 
That's why i was asking about locks at first place. 
And thanks for the advice, I will try to restructure to avoid using too many custom actions.

**Comment by Aldueen** [comment]
hi. i am encountering the same exception when using Entity Framework Data Provider. the configuration is pretty much basic and exactly the same as documentation. the exception occurs when i modify an entity and try to call SaveChanges() .
 here is the configuration code : 

`Configuration.Setup()
                .UseEntityFramework(ef => ef
                    .AuditTypeExplicitMapper(m => m
                        .Map<Case, AuditCase>()
                        .AuditEntityAction<IBaseAuditModel>((ev, ent, auditEntity) =>
                        {
                            auditEntity.AuditDate = DateTime.UtcNow;
                            auditEntity.UserName = ev.Environment.UserName;
                            auditEntity.AuditAction = ent.Action; // Insert, Update, Delete
                            auditEntity.CallerMethod = ev.Environment.CallingMethodName;
                        })
                    ));`

exception : 
`An exception of type 'System.InvalidOperationException' occurred in Web.dll but was not handled in user code
Collection was modified; enumeration operation may not execute.`

notes :
- save changes apply the modification to entity object but no audit record is written to database.
- the code works without problem when audit.net is out of the system.

thank you in advance for your help.

**Comment by thepirat000** [comment]
Please share the complete exception with the stacktrace

**Comment by Aldueen** [comment]
wow...thank you for quick response!. 
here is the stack trace : 

>    at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Data.Entity.Core.Objects.EntityEntry.TakeSnapshotOfRelationships()
   at System.Data.Entity.Core.Objects.Internal.EntityWrapperWithoutRelationships`1.TakeSnapshotOfRelationships(EntityEntry entry)
   at System.Data.Entity.Core.Objects.ObjectContext.AddSingleObject(EntitySet entitySet, IEntityWrapper wrappedEntity, String argumentName)
   at System.Data.Entity.Core.Objects.ObjectContext.AddObject(String entitySetName, Object entity)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassd.<Add>b__c()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet.Add(Object entity)
   at Audit.EntityFramework.Providers.EntityFrameworkDataProvider.InsertEvent(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEvent(Boolean forceInsert)
   at Audit.Core.AuditScope.Save()
   at Audit.EntityFramework.DbContextHelper.SaveScope(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditIdentityDbContext`1.SaveChanges()
   at PCI.Web.Services.CaseService.CaseService.EditCase(CaseEditViewModel model) in C:\Users\***\***\***\***\***\Services\CaseService\CaseService.cs:line 1451
   at PCI.Web.Controllers.CaseController.Edit(CaseEditViewModel model) in C:\Users\***\***\***\***\***\Controllers\CaseController.cs:line 257
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by Aldueen** [comment]
@thepirat000  here is some more detail : 
i had my audit table inherit from the entity being audited and an interface T so that my audit table mimic the original table structure plus some other properties . i modified the audit class to inherit just from the Interface. and then problem was solved.
now my question is :
