### ISSUE TITLE
ArgumentNullException when using the same owned entity type in OwnsOne or OwnsMany relationship

### ISSUE THREAD

**Issue by pergerch** [thepirat000/Audit.NET#373]
**Describe the bug**
This bug seems to be related to #360, I reported earlier. In the new case I am using the same entity as a single object and as a list. In my example ([here is the new branch in my test-repo](https://github.com/pergerch/AuditExample/tree/bug/owned-type-single-multiple)), we have a _department_ with just one _address_ and a _person_ that can have **multiple _addresses_**.

Adding a department or person and calling `SaveChanges` will throw a `ArgumentNullException` with the error being `Value cannot be null. (Parameter 'key')`

Again, when using `DbContext` instead of `AuditDbContext` it works.

**To Reproduce**

```
public class Department
{
	public int Id { get; set; }
	public string Name { get; set; }
	public Address Address { get; set; }
}

public class Person
{
	public int Id { get; set; }
	public string Name { get; set; }
	public List<Address> Addresses { get; set; }
}

public class Address
{
	public string City { get; set; }
	public string Street { get; set; }
}

```

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Person>().OwnsMany(x => x.Addresses);
	modelBuilder.Entity<Department>().OwnsOne(x => x.Address);
}
```

Stack trace:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Audit.EntityFramework.DbContextHelper.GetColumnValues(IAuditDbContext context, EntityEntry entry, EntityName entityName)
   at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at AuditExample.Program.Main(String[] args) in C:\P\Github\AuditExample\src\AuditExample\Program.cs:line 33
```

**Expected behavior**
No exception should be thrown and the audit information should be written.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 16.5.0

**Target .NET framework:**
 - .NET 5.0

**Comment by thepirat000** [comment]
Thanks for the code to reproduce the issue! 

I have fixed this on version 16.5.1, please upgrade and re-test.

Fix is on this line when obtaining the declaring type, now taking into account the ownership:

https://github.com/thepirat000/Audit.NET/blob/00f0836b2be388471ad740c6bc9f1a500822c740/src/Audit.EntityFramework/DbContextHelper.Core.cs#L169

**Comment by markhoebeke** [comment]
I ran into the same problem this weekend. I can confirm this update fixed the issue. Thanks!

**Comment by pergerch** [comment]
It also works for me now. Thank you for the update!
