### ISSUE TITLE
number_format_exception when using Elasticsearch data provider to audit Microsoft.Graph.PermissionScope

### ISSUE THREAD

**Issue by paolovalladolid** [thepirat000/Audit.NET#504]
We are getting this exception when the target is set to Microsoft.Graph.PermissionScope

```
HttpRequestException: 500 InternalServerError Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /developer-api-portal/_doc/5593da10-2080-40fb-ba37-89c94d113116. ServerError: Type: mapper_parsing_exception Reason: "failed to parse field [target.old.id] of type [float] in document with id '5593da10-2080-40fb-ba37-89c94d113116'. Preview of field's value: 'c7e83a25-d324-4a53-a464-c433a57360ba'" CausedBy: "Type: number_format_exception Reason: "For input string: "c7e83a25-d324-4a53-a464-c433a57360ba"""
at Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEventAsync(AuditEvent auditEvent)
at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
at Audit.Core.AuditScope.EndAsync()
at Audit.Core.AuditScope.DisposeAsync()
at Auditor.Auditor.AuditAsync(Object item, String KeyString)
at DataServiceApi.Controllers.ApiCardController.UpdateOauth2Permissions(PermissionScope scope, String id) in
```

The problem is PermissionScope has a property called Id, which is being treated as a number.

I found this discussion: https://github.com/thepirat000/Audit.NET/issues/152

However, I am having trouble implementing the AddCustomAction as the provided example relies on the method GetEntityFrameworkEvent which is not available in the Elasticesearch data provider.

**To Reproduce**
XUnit test

```
[Fact]
        public async void TestAuditPermissionScope()
        {
            var oddy = audit.GetAuditor(); // audit object is injected
            PermissionScope ps = new PermissionScope()
            {
                Id = new Guid("c7e83a25-d324-4a53-a464-c433a57360ba"),
                Type = "Admin",
                Value = "PaoloTestScope"
            };
            await oddy.AuditAsync(ps, "DevTestScope");
        }
```

Our wrapper class

```
public class Auditor : IAuditor
    {
        private readonly string indexName;
        private AuditScope auditScope;

        /// <summary>
        /// The indexName argument specifies which Elasticsearch index to use.  Behind the scenes,
        /// Auditor serializes the audit data (who did it, where, etc.) and the target object into a JSON
        /// document, then stores the document in Elasticsearch - aka "indexing" - at the provided index.
        /// </summary>
        /// <param name="indexName"></param>
        public Auditor(string indexName)
        {
            this.indexName = indexName;
        }

        /// <summary>
        /// Create an audit log document of the given object.
        /// </summary>
        /// <param name="item">The object to audit</param>
        /// <param name="KeyString">The string to use to identify the object, ideally in a way that makes it
        /// easy to search for in Elasticsearch</param>
        /// <returns></returns>
        public async Task AuditAsync(object item, string KeyString)
        {
            try
            {
                auditScope = await AuditScope.CreateAsync(indexName,
                    () => item,
                    new { KeyString = "" + KeyString });
            }
            finally
            {
                await auditScope.DisposeAsync();
            }
        }
    }
```

**Expected behavior**
The goal is to be able to audit changes to PermissionScope objects.

We understand that Audit.NET is not responsible for Elasticsearch behavior.  However, we need help on implementing a workaround such as a custom action, because we do not have access to the GetEntityFrameworkEvent method.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET.Elasticsearch":  19.1.4

**Target .NET framework:**
 - .NET 5

**Comment by thepirat000** [comment]
You cannot access the EF event because you are not generating EF events. But I don't see why would need the EF event in this case.

I think you still have the two options: (1) setting a dynamic template on elasticsearch, or (2) ensuring the property values are all of the same type across documents.

For (2), you could do something similar to this answer https://github.com/thepirat000/Audit.NET/issues/152#issuecomment-415591385, but for the Target.Old / Target.New properties, for example:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    if (scope.Event.Target.Old != null && !(scope.Event.Target.Old is string))
    {
        scope.Event.Target.Old = Audit.Core.Configuration.JsonAdapter.Serialize(scope.Event.Target.Old);
    }
    if (scope.Event.Target.New != null && !(scope.Event.Target.New is string))
    {
        scope.Event.Target.New = Audit.Core.Configuration.JsonAdapter.Serialize(scope.Event.Target.New);
    }
});
```

that will force the Target.Old and New to be stored as strings

**Comment by paolovalladolid** [comment]
Thanks.  I tried adding the above custom action and got this error

`Elasticsearch.Net.ElasticsearchClientException : Request failed to execute. Call: Status code 400 from: PUT /developer-api-portal/_doc/[some id string]. ServerError: Type: mapper_parsing_exception Reason: "object mapping for [target.old] tried to parse field [old] as object, but found a concrete value"`

I could look into Elasticsearch dynamic templates.  I guess I would have to use the Elasticsearch .NET Client to send the dynamic template in a PUT request, before using Audit.NET's Elasticsearch provider to send the serialized target.

**Comment by thepirat000** [comment]
does it fails if you use a fresh new index with no previous documents on it?
If soz can you provide a test that fails?

**Comment by thepirat000** [comment]
Closing this for inactivity, if you're still having this issue please comment and provide more details
