### ISSUE TITLE
Audit.EntityFramework.Core ClientConnectionId throws exception

### ISSUE THREAD

**Issue by sniperwolfpk5** [thepirat000/Audit.NET#518]
**My project setup**
- .net core 6.0
- EEf Core 6 with PostgreSQL provider. 
- Audit.Framework.Core library version latest 

![Screenshot 2022-08-12 123343](https://user-images.githubusercontent.com/11886702/184307418-6ae1e6b8-0ea2-4b0c-a5fb-a82f05506e76.png)

Trace
```
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) in /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs:line 124
   at Audit.EntityFramework.DbContextHelper.GetClientConnectionId(DbConnection dbConnection)
```
I faced exception when `_helper.SaveChangesAsync(_auditContext, () => base.SaveChangesAsync(cancellationToken));` function is called.

I downloaded the source code and debugged the code. The exception is thrown due to the `ClientConnectionId` being null. The exception occurred in the `DbContextHelper` class. The following is the function where the exception is thrown.

File Path: `Audit.EntityFramework > DbContextHelper.cs`
```
public string GetClientConnectionId(DbConnection dbConnection)
 {
            if (dbConnection == null)
            {
                return null;
            }
#if EF_CORE && (NETSTANDARD1_5 || NETSTANDARD2_0 || NETSTANDARD2_1 || NET472 || NET5_0_OR_GREATER )
            try
            {
                var connId = ((dbConnection as dynamic)?.ClientConnectionId) as Guid?;
                return connId.HasValue && !connId.Value.Equals(Guid.Empty) ? connId.Value.ToString() : null;
            }
            catch (Microsoft.CSharp.RuntimeBinder.RuntimeBinderException)
            {
                return null;
            }
#else
            // Get the connection id (returns NULL if the connection is not open)
            var sqlConnection = dbConnection as System.Data.SqlClient.SqlConnection;
            var connId = sqlConnection?.ClientConnectionId;
            return connId.HasValue && !connId.Value.Equals(Guid.Empty) ? connId.Value.ToString() : null;
#endif
}
```
This is how I configured audit library
```
public static void SetAuditContext(string connectionString)
{
    #region Audit
    var connection = connectionString;
    var auditDbCtxOptions = new DbContextOptionsBuilder<AuditContext>()
            .UseNpgsql(connection).Options;
    Audit.EntityFramework.Configuration.Setup()
       .ForContext<AuditContext>(config => config.IncludeEntityObjects()
        .AuditEventType("{AuditContext}:{database}"))
         .UseOptOut()
           .IgnoreAny(t => t.Name.EndsWith("AuditLog"));

    Audit.Core.Configuration.Setup()
    .UseEntityFramework(x => x
        .UseDbContext<AuditContext>(auditDbCtxOptions)
        .AuditTypeMapper(t => typeof(AuditLog))
        .AuditEntityAction<AuditLog>((ev, entry, entity) =>
        {
            entity.AuditData = Newtonsoft.Json.JsonConvert.SerializeObject(entry.GetEntry().Entity);
            entity.EntityType = entry.EntityType.Name;
            entity.AuditDate = DateTime.UtcNow;
            entity.Changes = entry.Changes.ToJson();
            entity.DatabaseName = ((AuditEventEntityFramework)ev).EntityFrameworkEvent.Database;
            entity.EntityType = entry.EntityType.FullName;
            entity.Action = entry.Action;
            entity.PrimaryKey = entry.PrimaryKey.ToJson();
            entity.Table = entry.Table;
            entity.UserId = ev.CustomFields["userId"]?.ToString();
            entity.UserName = ev.CustomFields["userName"]?.ToString();
            entity.RequestInfo = ev.CustomFields["requestInfo"]?.ToString();
        }).IgnoreMatchedProperties(true));
    #endregion
}
```

Can you tell me how to set `ClientConnectionId` when using `Ef Core 6` along with the PostgreSQL provider?
I haven't seen any property with the name `ClientConnectionId` in the 'DbConnection' class.

**Comment by thepirat000** [comment]
As you can see, the exception is user-handled. There is a catch in line 406:

https://github.com/thepirat000/Audit.NET/blob/8ae9a42dcad48a6a44e3130409fa909a83b0760d/src/Audit.EntityFramework/DbContextHelper.cs#L401-L409

So the function should return NULL for the ConnectionId when using the Postgres provider. 

I'm not sure if Postgres provides any kind of Connection ID, but if it does, maybe it can be retrieved and updated on a Custom Action, for example:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope => 
{
    var efEvent = scope.GetEntityFrameworkEvent();
    var dbConnection = efEvent.GetDbContext().Database.GetDbConnection(); // This will be a Npgsql.NpgsqlConnection
    efEvent.ConnectionId = GetConnectionId(dbConnection); 
});
```

**Comment by thepirat000** [comment]
Did you manage to solve this issue?
