### ISSUE TITLE
Using Postgresql + WebApi.Core produces the following exception 22P05: unsupported Unicode escape sequence 

### ISSUE THREAD

**Issue by lucax88x** [thepirat000/Audit.NET#566]
**Describe the bug**
Fails to create events and controllers stop working

**To Reproduce**
Add WebApi.Core, Postgresql and try to call a controller

**Expected behavior**
Expect it to create events in the table

**Libraries (specify the Audit.NET extensions being used including version):**
        <PackageReference Include="Audit.NET" Version="20.1.3" />
        <PackageReference Include="Audit.NET.PostgreSql" Version="20.1.3" />
        <PackageReference Include="Audit.WebApi.Core" Version="20.1.3" />

**Target .NET framework:**
 - .net 6.0

**Additional context**
The EF.Core works fine, It's just the web-api that fails

Btw. cool library. I'm testing it for a project.

**Comment by lucax88x** [comment]
full exception:

pgsql.PostgresException (0x80004005): 22P05: unsupported Unicode escape sequence

DETAIL: \u0000 cannot be converted to text.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Audit.PostgreSql.Providers.PostgreSqlDataProvider.InsertEventAsync(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
   at Audit.Core.AuditScope.EndAsync()
   at Audit.Core.AuditScope.DisposeAsync()
   at Audit.WebApi.AuditMiddleware.AfterInvoke(HttpContext context, Boolean includeResponseBody, Boolean includeResponseHeaders, Exception exception)
   at Audit.WebApi.AuditMiddleware.InvokeNextAsync(HttpContext context, Boolean includeResponseBody, Boolean includeResponseHeaders, Stream originalBody)
   at Audit.WebApi.AuditMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
  Exception data:
    Severity: ERROR
    SqlState: 22P05
    MessageText: unsupported Unicode escape sequence
    Detail: \u0000 cannot be converted to text.
    Where: JSON data, line 1: ..."Type":"application/json; charset=utf-8","Value":...
    File: jsonfuncs.c
    Line: 611
    Routine: json_ereport_error

**Comment by lucax88x** [comment]
keep in mind \u0000 is a null, so probably there's a null somewhere in the pipeline.

**Comment by lucax88x** [comment]
Looks like it happens using IncludeResponseHeaders and IncludeResponseBody

**Comment by thepirat000** [comment]
Can you share your PostgreSQL data provider configuration?

**Comment by thepirat000** [comment]
I'm thinking on adding a configuration for the PostgreSQL provider in order to allow the manipulation of the Json string before sending it to the database.

for example:

```c#
Audit.Core.Configuration.Setup()
    .UsePostgreSql(config => config
        .ConnectionString(...)
        .TableName("event")
        .IdColumnName("id")
        .DataColumn("data")
        .DataJsonValue(auditEvent => auditEvent.ToJson().Replace(@"\u0000", " "))
```

The `.DataJsonValue` will allow changing the way to generate the JSON string, so one option could be to just Replace the unwanted string.

**Comment by lucax88x** [comment]
```csharp
Audit.Core.Configuration
                .Setup()
                .UsePostgreSql(
                    config => config
                        .ConnectionString(dbConnectionString)
                        .Schema(Schema)
                        .TableName(Table)
                        .IdColumnName(IdColumn)
                        .DataColumn(DataColumn, DataType.JSONB)
                        .LastUpdatedColumnName(UpdatedDateColumn)
                );

app.UseAuditMiddleware(
            _ => _
                .FilterByRequest(rq => !Path.HasExtension(rq.Path.Value))
                // sensitive data, be careful
                // .WithEventType("{verb}:{url}")
                // .IncludeHeaders()
                // .IncludeResponseHeaders()
                // .IncludeRequestBody()
                // .IncludeResponseBody()
        );
```

**Comment by lucax88x** [comment]
> I'm thinking on adding a configuration for the PostgreSQL provider in order to allow the manipulation of the Json string before sending it to the database.
> 
> for example:
> 
> ```cs
> Audit.Core.Configuration.Setup()
>     .UsePostgreSql(config => config
>         .ConnectionString(...)
>         .TableName("event")
>         .IdColumnName("id")
>         .DataColumn("data")
>         .DataJsonValue(auditEvent => auditEvent.ToJson().Replace(@"\u0000", " "))
> ```
> 
> The `.DataJsonValue` will allow changing the way to generate the JSON string, so one option could be to just Replace the unwanted string.
> 
> Or maybe just as an overload of the existing `.DataColumn` fluent API, like:
> 
> ```cs
>         .DataColumn("data", ev => ev.ToJson().Replace(@"\u0000", " "))
> ```

I prefer the overload of DataColumn, seems more intuitive.

Imho callback with (event, json) => json.Replace(....);

So, you pass me the json you've already serialized, and I can work on it, but I also have the original event so I can do something with it if needed.

It's the same you said, just with more infos

**Comment by thepirat000** [comment]
An overload to `DataColumn()` fluent API was added that allows defining the way to obtain the JSON string from the AuditEvent. 

I did not add separated parameters as you suggested, for simplicity and to be similar to the `CustomColumn()` behavior.

This is included in version 20.1.4, please upgrade your references and re-test.

For example: 

```c#
Audit.Core.Configuration.Setup()
  .UsePostgreSql(c => c
    .ConnectionString(...)
    .DataColumn("data", DataType.JSONB, auditEvent => Sanitize(auditEvent.ToJson())));
```
