### ISSUE TITLE
UseElasticsearch entity update issue 

### ISSUE THREAD

**Issue by accacc** [thepirat000/Audit.NET#591]
Hello
I am using ElasticSearch as provider, but I am getting the following error in the update process. Could you help?

Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /servicelogs/_doc/927ae710-477c-4c71-9b13-cb596c285167. ServerError: Type: mapper_parsing_exception Reason: "object mapping for [interceptEvent.arguments.value] tried to parse field [value] as object, but found a concrete value"
   at Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEvent(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEvent(Boolean forceInsert)
   at Audit.Core.AuditScope.End()
   at Audit.DynamicProxy.AuditInterceptor.EndAsyncAuditInterceptEvent(Task task, IInvocation invocation, InterceptEvent intEvent, IAuditScope scope, Object result)
   at Audit.DynamicProxy.AuditInterceptor.InterceptAsync(Task task, IInvocation invocation, InterceptEvent intEvent, IAuditScope scope)
   at AuditTestApi.Controllers.ProductsController.Put(Int32 id, ProductEntity value) in C:\Users\bluet\source\repos\AuditTestApi\AuditTestApi\Controllers\ValuesController.cs:line 41
   at lambda_method200(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Audit.WebApi.AuditMiddleware.InvokeNextAsync(HttpContext context, Boolean includeResponseBody, Boolean includeResponseHeaders, Stream originalBody)
   at Audit.WebApi.AuditMiddleware.InvokeNextAsync(HttpContext context, Boolean includeResponseBody, Boolean includeResponseHeaders, Stream originalBody)
   at Audit.WebApi.AuditMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5266
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,nl;q=0.6
Content-Type: application/json
Cookie: Seq-Session=RFSEk49PKRaAy4RuE8IT6rlAJ9vnrXpuVWkCIWvV
Origin: http://localhost:5266
Referer: http://localhost:5266/swagger/index.html
Content-Length: 135
sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty

**Comment by thepirat000** [comment]
I think it's the same problem as for #152 ([here](https://github.com/thepirat000/Audit.NET/issues/152#issuecomment-415591385)) and #499. Please take a look.

The problem seems to be Elasticsearch's [Dynamic Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html). 

The first time you insert to the index, it will dynamically map the type of the result / arguments depending on its value, but they could hold an object or a concrete value. 

So, for example, if the first audited method was `void CreateOrder(Order order)`, then the audit arguments.value will be mapped as an object, but if the second audited method is `void GetOrder(int id)`, then the audit argument.value will be a concrete value and the index insertion will fail.

I think one way to solve it is to force all the "object" values, to be mapped as JSON objects, for example using a Custom Action that will execute before the audit event save operation:

```c#
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var interceptEvent = scope.GetAuditInterceptEvent();
    foreach (var arg in interceptEvent.Arguments)
    {
        arg.Value = ToJson(arg.Value);
    }

    interceptEvent.Result.Value = ToJson(interceptEvent.Result.Value);
});
```

**Comment by accacc** [comment]
ToJson method?

**Comment by thepirat000** [comment]
JsonSerializer.Serialize(interceptEvent.Result.Value), or whatever

**Comment by accacc** [comment]
Hello again,

interceptEvent is getting always null.

**Comment by thepirat000** [comment]
You should share your audit configuration and/or a sample minimal project that reproduces the issue

**Comment by accacc** [comment]
you can find a test project below link

https://github.com/accacc/AuditTestApi

**Comment by thepirat000** [comment]
interceptEvent will be null for any audit event that is not generated by Audit.DynamicProxy, for example the audit event generated by Audit.WebApi extension.

Also `interceptEvent.Arguments` will be NULL when the audited method has no parameters, so you should probably add some  validations.

Note that any argument passed to (or the result returned from) an audited proxied method should be JSON serializable, but your ProductService methods are returning DbSet<T> which is not serializable.

For this, you have two options:

- Ignore the audits for the entities that are not serializable

```c#
[return: AuditIgnore]  // Ignore the return value in the audits
public IEnumerable<ProductEntity?> GetProducts()
{
    return _dbContext.Products;  // Note this is a DbSet<ProductEntity>
}
```
or

- Return serializable entities from your methods
```c#
public IEnumerable<ProductEntity?> GetProducts()
{
    return _dbContext.Products.ToList();  // return a list
}
```

**Comment by thepirat000** [comment]
Closing this for inactivity. If you're still having the issue please comment below
